site_name: SmartHive Documentation
site_description: Documentación del ecosistema SmartHive basado en agentes inteligentes
site_author: Ricardo Reyes
repo_url: https://github.com/reyer3/smart_hive
repo_name: smart_hive
docs_dir: docs
site_dir: site

theme:
  font:
    text: Quicksand
    code: Ubuntu
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber   # Color principal de Google
      accent: yellow    # Color de acento de Google
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber  # Color principal para modo oscuro
      accent: yellow   # Color de acento para modo oscuro
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Architecture:
      - General: architecture/system_architecture.md
      - Agent Architecture: architecture/agent_architecture.md
      - Agent Ecosystem: architecture/agent_ecosystem.md
      - User Personalization: architecture/user_personalization.md
      - Data Model: architecture/data_model.md
  - Development:
      - Backend: development/backend_development.md
      - Frontend: development/frontend_development.md
      - Agent Development: development/agent_development.md
      - Deployment: development/deployment.md
      - Testing: development/testing.md
  - Workflows:
      - Agent Workflows: workflows/agent_workflows.md
      - CI/CD Pipeline: workflows/ci_cd_pipeline.md
      - Development Workflows: workflows/development_workflows.md
  - Roadmap:
      - Features: roadmap/features.md
      - Milestones: roadmap/milestones.md
      - Backlog: roadmap/backlog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reyer3
      name: GitHub
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY