site_name: SmartHive
site_description: Ecosistema SmartHive basado en agentes inteligentes.
site_author: Ricardo Reyes
repo_url: https://github.com/reyer3/smart_hive
repo_name: smart_hive
site_url: https://reyer3.github.io/smart_hive/
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    primary: amber
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Inicio: index.md
  - Guías:
      - Testing:
          - Testing LLM: testing/llm_testing.md
  - Roadmap:
      - Milestones: roadmap/milestones.md