site_name: SmartHive Documentation
site_description: Documentación del ecosistema SmartHive basado en agentes inteligentes
site_author: Ricardo Reyes
repo_url: https://github.com/reyer3/smart_hive
repo_name: smart_hive
site_url: https://reyer3.github.io/smart_hive/
docs_dir: docs
site_dir: site

theme:
  name: material
  language: es
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font:
    text: Quicksand
    code: Ubuntu Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - tags

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Architecture:
      - System Architecture: architecture/system_architecture.md
      - Agent Architecture: architecture/agent_architecture.md
      - Agent Ecosystem: architecture/agent_ecosystem.md
      - User Personalization: architecture/user_personalization.md
      - Data Model: architecture/data_model.md
  - Development:
      - Backend: development/backend_development.md
      - Frontend: development/frontend_development.md
      - Agent Development: development/agent_development.md
      - Deployment: development/deployment.md
      - Testing: development/testing.md
  - Workflows:
      - Agent Workflows: workflows/agent_workflows.md
      - CI/CD Pipeline: workflows/ci_cd_pipeline.md
      - Development Workflows: workflows/development_workflows.md
  - ADRs:
      - Overview: adr/README.md
      - Framework Selection: adr/001-agent-framework-selection.md
  - Roadmap:
      - Features: roadmap/features.md
      - Milestones: roadmap/milestones.md
      - Backlog: roadmap/backlog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reyer3
      name: GitHub
  analytics:
    provider: google
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.