site_name: SmartHive
site_description: Ecosistema SmartHive basado en agentes inteligentes.
site_author: Ricardo Reyes
repo_url: https://github.com/reyer3/smart_hive
repo_name: smart_hive
site_url: https://reyer3.github.io/smart_hive/
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Inicio: index.md
  - Arquitectura:
      - Sistema: architecture/system_architecture.md
      - Agentes:
          - Arquitectura: architecture/agent_architecture.md
          - Comunicación: architecture/agent_communication.md
          - Ecosistema: architecture/agent_ecosystem.md
      - Modelo de Datos: architecture/data_model.md
      - Personalización: architecture/user_personalization.md
  - Desarrollo:
      - Backend: development/backend_development.md
      - Frontend: development/frontend_development.md
      - Agentes: development/agent_development.md
      - Testing: development/testing.md
      - Despliegue: development/deployment.md
  - Flujos de Trabajo:
      - Agentes:
          - Colaboración: workflows/agent_collaboration.md
          - Flujos: workflows/agent_workflows.md
      - CI/CD: workflows/ci_cd_pipeline.md
      - Desarrollo: workflows/development_workflows.md
  - Testing:
      - LLM Testing: testing/llm_testing.md
  - ADRs:
      - Overview: adr/README.md
      - Framework Selection: adr/001-agent-framework-selection.md
  - Roadmap:
      - Features: roadmap/features.md
      - Milestones: roadmap/milestones.md
      - Backlog: roadmap/backlog.md