name: ci
on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          pip install mkdocs-material \
                      mkdocs-material-extensions \
                      pillow \
                      cairosvg \
                      pygments \
                      pymdown-extensions

      - name: Build and validate
        run: |
          mkdocs build --strict --verbose --config-file mkdocs.yml

      - name: Deploy
        run: |
          mkdocs gh-deploy --force --clean --config-file mkdocs.yml --verbose
